name: Build

on:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
      - name: Install dependenicies
        run: |
          yum -y install file gcc gcc-c++ make zlib-devel
      - name: Build
        run: |
          make
          strip out-shared/libleveldb.so.1.20
          file out-shared/libleveldb.so.1.20
          ldd out-shared/libleveldb.so.1.20
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out-shared/libleveldb.so
          asset_name: libleveldb.so
          asset_content_type: so
  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out-shared/libleveldb.dylib
          asset_name: libleveldb.dylib
          asset_content_type: dylib
